[package]
name = "gi_t"
version = "0.0.1"
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"
description = "A git typo handler."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
